linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - bodyclose
    - nilerr
    - exportloopref
    - prealloc
    - unconvert

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too strict for clean domain types
  goimports:
    local-prefixes: github.com/tutu-network/tutu
  misspell:
    locale: US

issues:
  exclude-rules:
    # Test files can be more relaxed
    - path: _test\.go
      linters:
        - errcheck
        - bodyclose
    # Domain types don't need all govet checks
    - path: internal/domain/
      linters:
        - govet
      text: "fieldalignment"
    # API handlers: w.Write/enc.Encode errors are rarely actionable
    - path: internal/api/
      linters:
        - errcheck
    # Prealloc is advisory, not a correctness issue
    - linters:
        - prealloc
      text: "Consider pre-allocating"

run:
  timeout: 5m
  tests: true
  build-tags: []

output:
  formats:
    - format: colored-line-number
  sort-results: true
